spring:
  application:
    name: EDU-SERVICE
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/online_edu?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  redis:
    host: 121.41.228.140
    port: 6380
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8888/eureka/
#  instance:
#    appname: EDU-SERVICE
#    prefer-ip-address: true
server:
  port: 8000
swagger2:
  enable: true
mybatis-plus:
  mapper-locations: classpath:com/atguigu/edu/mapper/xml/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl