spring:
  application:
    name: EDU-USER
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/online_edu?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  redis:
    host: 182.92.234.71
    port: 6379

server:
  port: 8150
swagger2:
  enable: true
mybatis-plus:
  mapper-locations: classpath:com/atguigu/edu/mapper/xml/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

sms:
  accessKeyId: LTAI4FxsK9JSReknyhkHTKSV
  accessKeySecret: CVKyxxf57WPy49XSxOeCum2B4DiCyd
  SignName: 谷粒学院教育网站
  TemplateCode: SMS_185820314
wx:
  open:
    # 微信开放平台 appid
    app_id: wxed9954c01bb89b47
    # 微信开放平台 appsecret
    app_secret: a7482517235173ddb4083788de60b90e
    # 微信开放平台 重定向url（guli.shop需要在微信开放平台配置）
    redirect_url: http://guli.shop/api/ucenter/wx/callback